import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect,useState } from "react";
import { toast } from "sonner";
import { requireSupabase } from "@/lib/supabase";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route=createFileRoute("/admin")({component:Admin});
type User={id:string;full_name:string;username:string;email:string;phone:string;country:string;status:string;payment_status:string;balance:number;created_at:string};
function Admin(){
 const nav=useNavigate(); const [session,setSession]=useState<any>(null); const [users,setUsers]=useState<User[]>([]); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [title,setTitle]=useState("Moxera"); const [message,setMessage]=useState("");
 const db=(()=>{try{return requireSupabase()}catch{return null}})();
 async function check(){if(!db)return;const {data}=await db.auth.getSession(); if(!data.session)return; const {data:a}=await db.from("moxera_admins").select("user_id").eq("user_id",data.session.user.id).maybeSingle(); if(a)setSession(data.session);else await db.auth.signOut();}
 async function login(e:FormEvent){e.preventDefault();setBusy(true);try{if(!db)throw new Error("Supabase haijawekwa.");const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;await check();}catch(e:any){toast.error(e?.message||"Admin login imeshindikana.");}finally{setBusy(false);}}
 async function load(){if(!db)return;const {data,error}=await db.from("moxera_users").select("*").order("created_at",{ascending:false});if(error)toast.error(error.message);else setUsers(data||[]);}
 useEffect(()=>{check()},[]); useEffect(()=>{if(session)load()},[session]);
 async function update(id:string,patch:any){if(!db)return;const {error}=await db.from("moxera_users").update(patch).eq("id",id);if(error)toast.error(error.message);else{toast.success("Imebadilishwa.");load();}}
 async function approve(u:User){if(!db)return;const {error}=await db.from("moxera_users").update({status:"active",payment_status:"paid"}).eq("id",u.id);if(!error)await db.from("moxera_payments").update({status:"paid"}).eq("user_id",u.id).eq("status","pending");if(error)toast.error(error.message);else{toast.success("User ame-activate.");load();}}
 async function send(target:string|null){if(!db||!title||!message)return;const {data:all}=target?{data:[{id:target}]}:await db.from("moxera_users").select("id");const rows=(all||[]).map((u:any)=>({user_id:u.id,title,message,is_broadcast:false}));if(!target)rows.push({user_id:null,title,message,is_broadcast:true});const {error}=await db.from("moxera_notifications").insert(rows);if(error)toast.error(error.message);else{toast.success("Notification imetumwa.");setMessage("");}}
 if(!session)return <main className="flex min-h-screen items-center justify-center bg-background px-4"><form onSubmit={login} className="w-full max-w-md rounded-3xl bg-card p-6 shadow-xl"><h1 className="text-2xl font-extrabold">Admin Panel</h1><p className="mt-1 text-sm text-muted-foreground">Ingiza admin email na password.</p><div className="mt-6 space-y-3"><Input type="email" placeholder="Admin email" required value={email} onChange={e=>setEmail(e.target.value)}/><Input type="password" placeholder="Password" required value={password} onChange={e=>setPassword(e.target.value)}/><Button disabled={busy} className="w-full">{busy?"Inaingia…":"Login"}</Button></div></form></main>;
 return <main className="min-h-screen bg-background p-4"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-extrabold">Admin Panel</h1><p className="text-sm text-muted-foreground">Users, payments & notifications</p></div><Button variant="outline" onClick={async()=>{await db?.auth.signOut();nav({to:"/"})}}>Toka</Button></div>
 <section className="mt-5 rounded-2xl bg-card p-4"><h2 className="font-bold">Notification</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><Input placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)}/><Input placeholder="Message" value={message} onChange={e=>setMessage(e.target.value)}/></div><div className="mt-3 flex gap-2"><Button onClick={()=>send(null)}>Tuma kwa wote</Button></div></section>
 <section className="mt-5 overflow-x-auto rounded-2xl bg-card p-4"><h2 className="mb-3 font-bold">Users ({users.length})</h2><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b"><th className="p-2">User</th><th className="p-2">Phone</th><th className="p-2">Payment</th><th className="p-2">Status</th><th className="p-2">Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-border"><td className="p-2"><b>{u.username}</b><div className="text-xs text-muted-foreground">{u.full_name}<br/>{u.email}</div></td><td className="p-2">{u.phone}</td><td className="p-2">{u.payment_status}</td><td className="p-2">{u.status}</td><td className="p-2"><div className="flex flex-wrap gap-1">{u.status!=="active"&&<Button size="sm" onClick={()=>approve(u)}>Approve</Button>}{u.status!=="banned"?<Button size="sm" variant="destructive" onClick={()=>update(u.id,{status:"banned"})}>Ban</Button>:<Button size="sm" variant="outline" onClick={()=>update(u.id,{status:"active"})}>Unban</Button>}<Button size="sm" variant="outline" onClick={()=>send(u.id)}>Notify</Button></div></td></tr>)}</tbody></table></section></div></main>
}
